allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': set this to true or false
  '@prisma/engines': true
  '@swc/core': true
  better-sqlite3: false
  esbuild: true
  msw: true
  prisma: true
  sharp: true
